apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chores.name" . }}
  labels:
    {{- include "chores.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.secret.secretKey | quote }}
